### ISSUE TITLE
Typo in Problem Sheet 2

### ISSUE THREAD

**Issue by jiaminglimjm** [ImperialCollegeLondon/M40001_lean#1]
Hello! I spotted a small typo in the definition of continuity while doing [problem sheet 2](https://github.com/ImperialCollegeLondon/M40001_lean/blob/master/src/2020/problem_sheets/sheet2.lean#L104) in lean.

I believe it should have been the top row, rather than bottom
```lean
¬ (∀ ε : ℝ, ε > 0 → ∃ δ : ℝ, δ > 0 ∧ ∀ y : ℝ, abs (y - x) < δ → abs (f y - f x) < ε)
¬ (∀ ε : ℝ, ε > 0 → ∃ δ : ℝ, δ > 0 → ∀ y : ℝ, abs (y - x) < δ → abs (f y - f x) < ε)
```

**Comment by kbuzzard** [comment]
You're right! Thanks!
