### ISSUE TITLE
Typo in README.md in functions

### ISSUE THREAD

**Issue by Laheau** [ImperialCollegeLondon/M40001_lean#4]
there is a typo on the last sentence of the README.md file in [M40001_lean/src/2021/functions/](https://github.com/ImperialCollegeLondon/M40001_lean/tree/master/src/2021/functions) folder.

> and if you're stuck then ~~yu~~ you can [watch the relevant videos in the playlist](https://www.youtube.com/playlist?list=PLVZep5wTamMmeF968ovIjd-uc1I6kdirJ).

**Comment by kbuzzard** [comment]
Only just saw this. Fixed! Thanks!
